# Module: NumPy Assignments

## Lesson: NumPy

In [1]:
import numpy as np

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [5]:
# import random

# arr = np.array([[random.randint(1, 20) for _ in range(5)] for _ in range(5)])
arr = np.random.randint(1, 21, size=(5, 5))
print("Original Array")
print(arr)

print()

arr[:, 2] = 1
print("Modified Array")
print(arr)

Original Array
[[ 8 14 14  3 19]
 [ 5 14 20  8 17]
 [ 1 13  4 20 14]
 [ 3  2 13 10 20]
 [12  5  6  3 17]]

Modified Array
[[ 8 14  1  3 19]
 [ 5 14  1  8 17]
 [ 1 13  1 20 14]
 [ 3  2  1 10 20]
 [12  5  1  3 17]]


In [13]:
# arr = np.arange(1, 17).reshape(4, 4)
arr = np.arange(1, 17).reshape((4, 4))
print("Original Array")
print(arr)

print()

# for i in range(4):
#     arr[i, i] = 0
np.fill_diagonal(arr, 0)
print("Modified Array")
print(arr)

Original Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Modified Array
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [15]:
arr = np.arange(1, 37).reshape(6, 6)
print(arr)

print()

sub_arr = arr[2:5, 1:4]
print(sub_arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [18]:
arr = np.random.randint(1, 21, size=(5, 5))
print(arr)

print()

border_elements = np.concatenate((arr[0, :], arr[-1, :], arr[1:-1, 0], arr[1:-1, -1]))
print(border_elements)

[[ 8 13  3  2 18]
 [ 9 12 12  6 19]
 [11  5  4 14 15]
 [ 3 15 12 10 19]
 [ 3 19 18 11 14]]

[ 8 13  3  2 18  3 19 18 11 14  9 11  3 19 15 19]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [20]:
arr1 = np.random.randint(1, 13, size=(3, 4))
arr2 = np.random.randint(1, 13, size=(3, 4))

print(arr1)
print(arr2)

print()
print("Addition")
print(arr1 + arr2)

print()
print("Substraction")
print(arr1 - arr2)

print()
print("Multiplication")
print(arr1 * arr2)

print()
print("Division")
print(arr1 / arr2)

[[12  2 12 12]
 [ 1  1  2  8]
 [ 3  7  4  7]]
[[ 4  3  4  3]
 [ 4 12  5  1]
 [ 4  3  3  6]]

Addition
[[16  5 16 15]
 [ 5 13  7  9]
 [ 7 10  7 13]]

Substraction
[[  8  -1   8   9]
 [ -3 -11  -3   7]
 [ -1   4   1   1]]

Multiplication
[[48  6 48 36]
 [ 4 12 10  8]
 [12 21 12 42]]

Division
[[3.         0.66666667 3.         4.        ]
 [0.25       0.08333333 0.4        8.        ]
 [0.75       2.33333333 1.33333333 1.16666667]]


In [22]:
arr = np.arange(1, 17).reshape(4, 4)
print(arr)

row_sum = np.sum(arr, axis=1)
column_sum = np.sum(arr, axis=0)

print(row_sum)
print(column_sum)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[10 26 42 58]
[28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [23]:
arr = np.random.randint(1, 21, size=(5, 5))
print(arr)

print()
print("Mean")
print(np.mean(arr))

print()
print("Median")
print(np.median(arr))

print()
print("Standard Deviation")
print(np.std(arr))

print()
print("Variance")
print(np.var(arr))

[[ 1  4  8  7  8]
 [ 4 14 15 17  8]
 [ 3 11  4  8 10]
 [15 19 12 17 18]
 [16 18  3  4  6]]

Mean
10.0

Median
8.0

Standard Deviation
5.578530272392541

Variance
31.12


In [24]:
arr = np.arange(1, 10).reshape(3, 3)
print(arr)

print()
mean = np.mean(arr)
std_dev = np.std(arr)
normalized_arr = (arr - mean) / std_dev
print(mean, std_dev)

print()
print(normalized_arr)
print(np.mean(normalized_arr), np.std(normalized_arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

5.0 2.581988897471611

[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
0.0 1.0


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [28]:
arr = np.random.randint(1, 10, size=(3, 3))
print(arr)

arr_to_add = np.array([1, 2, 3])
print(arr_to_add)

print(arr + arr_to_add)

[[3 4 6]
 [8 5 5]
 [7 5 4]]
[1 2 3]
[[4 6 9]
 [9 7 8]
 [8 7 7]]


In [30]:
arr = np.random.randint(1, 17, size=(4, 4))
print(arr)

arr_to_substract = np.array([1, 2, 3, 4])
print(arr_to_substract)

print(arr - arr_to_substract[:, np.newaxis])

[[ 9  8  5 12]
 [10 15  8 16]
 [ 6 10 15 12]
 [ 8  9  2 11]]
[1 2 3 4]
[[ 8  7  4 11]
 [ 8 13  6 14]
 [ 3  7 12  9]
 [ 4  5 -2  7]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [31]:
matrix = np.random.randint(1, 10, size=(3, 3))
print(matrix)

determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)

eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues:", eigenvalues)

[[6 6 7]
 [5 1 2]
 [9 7 1]]
Determinant: 182.0000000000001
Inverse:
[[-0.07142857  0.23626374  0.02747253]
 [ 0.07142857 -0.31318681  0.12637363]
 [ 0.14285714  0.06593407 -0.13186813]]
Eigenvalues: [15.04958622 -4.09995461 -2.94963162]


In [33]:
matrix_1 = np.random.randint(1, 6, size=(2, 3))
matrix_2 = np.random.randint(1, 6, size=(3, 2))

print(matrix_1)
print(matrix_2)

print("Result")
print(np.dot(matrix_1, matrix_2))

[[4 1 3]
 [5 3 1]]
[[4 4]
 [1 4]
 [1 4]]
Result
[[20 32]
 [24 36]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [34]:
arr = np.arange(1, 10).reshape(3, 3)
print(arr)

arr = arr.reshape(1, 9)
print(arr)

arr = arr.reshape(9, 1)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [35]:
arr = np.random.randint(1, 10, size=(5, 5))
print(arr)

arr = arr.flatten()
print(arr)

arr = arr.reshape(5, 5)
print(arr)

[[2 7 7 7 2]
 [9 5 2 7 1]
 [6 1 2 5 9]
 [6 9 2 2 8]
 [4 1 7 9 6]]
[2 7 7 7 2 9 5 2 7 1 6 1 2 5 9 6 9 2 2 8 4 1 7 9 6]
[[2 7 7 7 2]
 [9 5 2 7 1]
 [6 1 2 5 9]
 [6 9 2 2 8]
 [4 1 7 9 6]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [36]:
arr = np.random.randint(1, 10, size=(5, 5))
print(arr)

print()
corners = arr[[0, 0, -1, -1], [0, -1, 0, -1]]
print(corners)

[[2 2 2 8 7]
 [7 5 5 6 9]
 [6 8 8 8 7]
 [5 1 6 4 4]
 [5 1 1 7 6]]

[2 7 5 6]


In [38]:
arr = np.random.randint(1, 21, size=(4, 4))
print(arr)

print()
arr[arr > 10] = 10
print(arr)

[[16  2 16 20]
 [15  6 10 11]
 [12 10 14 14]
 [ 1  6 19  3]]

[[10  2 10 10]
 [10  6 10 10]
 [10 10 10 10]
 [ 1  6 10  3]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [54]:
data_types = [("name", 'U10'), ("age", "i4"), ("weight", "f4")]
arr = np.array([("Andresuperlong", 19, 54), ("Alya", 20, 48.3), ("Endriano", 19, 70)], dtype=data_types)
print(arr)

print()
# sorted_data = np.sort(arr, order="age")
sorted_data = np.sort(arr, order="age")[::-1]
print(sorted_data)

[('Andresuper', 19, 54. ) ('Alya', 20, 48.3) ('Endriano', 19, 70. )]

[('Alya', 20, 48.3) ('Endriano', 19, 70. ) ('Andresuper', 19, 54. )]


In [49]:
data_types = [("x", "i4"), ("y", "i4")]
arr = np.array([(4, 8), (10, 16), (20, 30)], dtype=data_types)
print(arr)

print()
print(arr["x"])
# print(arr["x"][:, np.newaxis])
print(arr["x"][np.newaxis, :])
distances = np.sqrt((arr["x"][:, np.newaxis] - arr["x"]) ** 2 + (arr["y"][:, np.newaxis] - arr["y"]) ** 2)
print(distances)

[( 4,  8) (10, 16) (20, 30)]

[ 4 10 20]
[[ 4 10 20]]
[[ 0.         10.         27.20294102]
 [10.          0.         17.20465053]
 [27.20294102 17.20465053  0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [50]:
import numpy.ma as ma

arr = np.random.randint(1, 21, size=(4, 4))
masked_arr = ma.masked_greater(arr, 10)
print(arr)
print(masked_arr)

sum_unmasked = masked_arr.sum()
print(sum_unmasked)

[[17  7 14  8]
 [16 10  6 20]
 [ 1 10  4  2]
 [13 20  7 17]]
[[-- 7 -- 8]
 [-- 10 6 --]
 [1 10 4 2]
 [-- -- 7 --]]
55


In [53]:
arr = np.random.randint(1, 10, size=(3, 3))
masked_arr = ma.masked_array(arr, mask=np.eye(3, dtype=bool))
print(arr)
print(masked_arr)

print()
print(type(masked_arr[0][0]))
mean_unmasked = masked_arr.mean()
masked_arr = masked_arr.filled(mean_unmasked)
print(masked_arr)

[[2 2 1]
 [6 2 3]
 [6 7 5]]
[[-- 2 1]
 [6 -- 3]
 [6 7 --]]

<class 'numpy.ma.core.MaskedConstant'>
[[4 2 1]
 [6 4 3]
 [6 7 4]]
