## Array

In [15]:
import numpy as np

## create array using numpy
## create 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [16]:
arr2 = np.array((1, 2, 3, 4, 5))
print(arr2)
print(type(arr2))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [17]:
print(arr1.shape)
print(arr2.shape)

(5,)
(5,)


In [18]:
arr3 = np.array([1, 2, 3, 4, 5])
arr3.reshape(1, 5) ## 1 row and 5 columns
## fungsi reshape() mengembalikan array baru yang bentuknya sudah diubah, tetapi tidak memodifikasi arr3 itu sendiri
arr_changed = arr3.reshape(1, 5)

print(arr3)
print(arr_changed)
print(arr3.shape)
print(arr_changed.shape)

[1 2 3 4 5]
[[1 2 3 4 5]]
(5,)
(1, 5)


In [ ]:
## 2D Array
arr3 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr3)
print(arr3.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [21]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [22]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [24]:
one = np.ones((3, 4))

print(one)
print(type(one[0][0]))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<class 'numpy.float64'>


In [25]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## attributes of numpy array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype) ## may vary based on platform
print(arr.itemsize, "bytes") ## may vary based on platform

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64
8 bytes


## Vectorized Operation

In [29]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

## element wise addition
print("Addition", arr1 + arr2)

## element wise substraction
print("Substraction", arr1 - arr2)

## element wise multiplication
print("Multiplication", arr1 * arr2)

## element wise division
print("Division", arr1 / arr2)

Addition [11 22 33 44 55]
Substraction [ -9 -18 -27 -36 -45]
Multiplication [ 10  40  90 160 250]
Division [0.1 0.1 0.1 0.1 0.1]


In [ ]:
## universal functions
arr = np.array([2, 3, 4, 5, 6])

## square root
print(np.sqrt(arr))

## exponential
print(np.exp(arr))

## sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [32]:
## array slicing and indexing
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [40]:
print(arr[0][0])
print(arr[0:2, 2:])

1
[[3 4]
 [7 8]]


In [37]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [44]:
print(arr[1:, 1:3])

[[ 6  7]
 [10 11]]


In [45]:
## modify array elements
arr[0, 0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [46]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [51]:
## statistical concepts -- normalization
## to have a mean of 0 and stand)ard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized Data:", normalized_data)

mean = np.mean(normalized_data)
std_dev = np.std(normalized_data)
print("Mean after normalization:", mean)
print("Standard deviation after normalization:", std_dev)

Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Mean after normalization: 0.0
Standard deviation after normalization: 0.9999999999999999


In [52]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

## mean
mean = np.mean(data)
print("Mean:", mean)

## median
median = np.median(data)
print("Median:", median)

## standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

## variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [ ]:
## logical operation
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(data > 5)
print(data[data > 5])
print(data[(data > 5) & (data < 8)])
# print(type(data > 5))

## note: & untuk bitwise, and untuk menggabungkan dua nilai boolean tunggal

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[6 7]
